# Generated by Django 3.0.6 on 2020-06-15 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
    ]
