# Generated by Django 3.0.6 on 2020-06-17 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_api', '0004_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='sample',
            field=models.ImageField(blank=True, null=True, upload_to='certificate_templates/%Y%m%d'),
        ),
    ]
