# Generated by Django 3.0.6 on 2020-06-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_api', '0006_auto_20200617_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='names_file',
            field=models.FileField(blank=True, default='', upload_to='names_files'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='template_img',
            field=models.ImageField(blank=True, default='', upload_to='certificate_templates'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='template_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
