# Generated by Django 3.0.6 on 2020-06-19 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certgen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_name', models.CharField(max_length=50)),
                ('template_img', models.ImageField(blank=True, default='', upload_to='certificate_templates')),
                ('template_url', models.URLField(blank=True, default='')),
                ('names_csv', models.TextField(blank=True, default='')),
                ('names_file', models.FileField(blank=True, default='', upload_to='names_files')),
            ],
        ),
        migrations.RemoveField(
            model_name='tutorialseries',
            name='tutorial_category',
        ),
        migrations.DeleteModel(
            name='Tutorial',
        ),
        migrations.DeleteModel(
            name='TutorialCategory',
        ),
        migrations.DeleteModel(
            name='TutorialSeries',
        ),
    ]
