# Generated by Django 3.0.6 on 2020-07-20 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certgen', '0002_auto_20200619_1005'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificate',
        ),
    ]
